// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: delete.sql

package db

import (
	"context"
)

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM
	admin
WHERE
	id = ?
`

func (q *Queries) DeleteAdmin(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAdmin, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM
	session
WHERE
	id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}
