// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Admin struct {
	ID        string
	FirstName string
	LastName  string
	Email     string
	Superuser int64
	CreatedAt int64
	UpdatedAt int64
}

type Credential struct {
	AdminID      string
	PasswordHash []byte
	CreatedAt    int64
	UpdatedAt    int64
}

type Experiment struct {
	ID            string
	Name          string
	UrlPath       string
	DirectoryPath string
	MaxTrials     int64
	Status        int64
	CreatedBy     string
	CreatedAt     int64
	UpdatedAt     int64
}

type Session struct {
	ID      string
	AdminID string
	Expiry  int64
}

type Trial struct {
	ID           string
	ExperimentID string
	Data         []byte
	CreatedAt    int64
	UpdatedAt    int64
}
