// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: read.sql

package db

import (
	"context"
)

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT
	id, first_name, last_name, email, superuser, created_at, updated_at
FROM
	admin
WHERE
	email = ?
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Superuser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT
	id, admin_id, expiry
FROM
	session
WHERE
	id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(&i.ID, &i.AdminID, &i.Expiry)
	return i, err
}
