// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: update.sql

package db

import (
	"context"
)

const updateAdminInfo = `-- name: UpdateAdminInfo :one
UPDATE
	admin
SET
	email = ?,
	superuser = ?
WHERE
	id = ?
RETURNING
	id, first_name, last_name, email, superuser, created_at, updated_at
`

type UpdateAdminInfoParams struct {
	Email     string
	Superuser int64
	ID        string
}

func (q *Queries) UpdateAdminInfo(ctx context.Context, arg UpdateAdminInfoParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, updateAdminInfo, arg.Email, arg.Superuser, arg.ID)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Superuser,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE
	credential
SET
	password_hash = ?
WHERE
	admin_id = ?
`

type UpdatePasswordParams struct {
	PasswordHash []byte
	AdminID      string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.AdminID)
	return err
}
